{% set name = "hyperframe" %}
{% set version = "5.2.0" %}
{% set sha256 = "a9f5c17f2cc3c719b917c4f33ed1c61bd1f8dfac4b1bd23b7c80b3400971b41f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - hyperframe

about:
  home: http://python-hyper.org/hyperframe/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Pure-Python HTTP/2 framing '
  dev_url: https://github.com/python-hyper/hyperframe

extra:
  recipe-maintainers:
    - primozgodec
    - astaric
