travis:
  secure:
    BINSTAR_TOKEN: K3NZcbXNolpF4UROIlMMcwMUNOf3D9P1Oy+aPUwO0amf7oiYtM2FBfo7KhgyMJxWLGGLmgxV17wr8X69QvCWCHu81ghiTc59APdF5BKl8V2OraRRzKQvvXDlzrigHEtXBmwoDUziLKjx9iUIvTN1+21FMI3wuNulRZ0hti1HPgBJZkYFZZ5aUKnPX1jwSg5X3Q8Hd/GH3CmNajIQn2A/daF+tUiZq5X8bIVkBxTu0ssCdthZSnWAoAjFrI8G8DYdWYH62frb/IAoM1H6kEyb5XiyRa+9xmmXcGkOaZ/1zPWn+AD1qwuLSuEPuuCjS71wzq1Bqplt0xyRbtUhjXJPCYc9DBy0DF6j6cGZyohhElwxf1lI26HcidhEwFX2Oq1ZrjM741Y4ikNf4pGhOJXbyiQZ7pKX/QoZlvIczrviMZnsg/vQTBRWZsBXpFk7Rn3FOs0bD+QQoBHKClCXOHfmrJbIhyzGy49jcASP3YjRYi8qO9gwETukzJceoN2bTeRGzVkWfgw78cSMeGJc82T9xmrCkSiTs27knFku5pFqLsr9YuRuKtRqu0YYLKlafS6/7MVyiO5bo6gaAPvQ2nnOeoHP4hLX7orqcAA2wTEW+e9ne2+egcBzdv85JJLishv4dOiLMsvF6JiqrOP5eDxLWtq1WYGWEiB0ITwhF6yelLY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
